[book]
authors = ["Ludwig Thouvenin, William Smith, Joseph Noorchashm"]
language = "en"
multilingual = false
src = "book"
title = "Brontes Book"
description = "A book on all things brontes & mev"

[output.html]
theme = "book/theme"
git-repository-url = "https://github.com/SorellaLabs/brontes"
default-theme = "ayu"
no-section-label = true
mathjax-support = true

[output.html.fold]
enable = true
level = 1

[build]
build-dir = "target/book"

[rust]
edition = "2021" 