[package]
name = "brontes"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
# poirot
brontes-core.workspace = true
brontes-inspect.workspace = true
brontes-types.workspace = true
brontes-classifier.workspace = true
brontes-database.workspace = true
brontes-metrics.workspace = true
brontes-pricing.workspace = true
brontes-tracing.workspace = true
malachite.workspace = true
toml = "0.8.2"

# Async
tokio = { workspace = true, features = ["full", "tracing"] }
async-scoped = { version = "0.7.1", features = ["use-tokio"] }
futures.workspace = true

reqwest.workspace = true
# Reth
reth-tasks.workspace = true
reth-rpc.workspace = true
reth-rpc-api.workspace = true
reth-rpc-types.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-network-api.workspace = true
reth-primitives.workspace = true
reth-db.workspace = true
reth-blockchain-tree.workspace = true
reth-beacon-consensus.workspace = true
#reth-revm.workspace = true
reth-interfaces.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-sol-macro = { workspace = true, features = ["json"] }
alloy-sol-types = { workspace = true, features = ["json"] }

alloy-providers.workspace = true
alloy-transport-http.workspace = true
alloy-transport.workspace = true
alloy-network.workspace = true
alloy-json-rpc.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-client.workspace = true

# tracing
tracing.workspace = true
tracing-subscriber.workspace = true
reth-tracing-ext.workspace = true
colored.workspace = true

# misc
eyre.workspace = true
dotenv.workspace = true
num_cpus.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true

# http/rpc
hyper.workspace = true

# cli
clap = { version = "4.4.6", features = ["derive"] }

# logging
indoc = "2"
rayon.workspace = true
cfg-if = "1.0.0"

# prometheus
metrics-process.workspace = true
itertools.workspace = true


[features]
sorella-server = ["local-reth", "local-clickhouse"]
tests = [
  "brontes-core/tests",
  "brontes-database/tests",
  "brontes-classifier/tests",
  "brontes-inspect/tests",
]

local-reth = [
  "brontes-core/local-reth",
  "brontes-database/local-reth",
  "brontes-types/local-reth",
  "brontes-pricing/local-reth",
  "brontes-inspect/local-reth",
  "reth-tracing-ext/local-reth",
]

local-clickhouse = [
  "brontes-database/local-clickhouse",
  "brontes-core/local-clickhouse",
  "brontes-inspect/local-clickhouse",
  "brontes-classifier/local-clickhouse",
]
uni-v3-ticks = ["brontes-pricing/uni-v3-ticks"]
dyn-decode = ["brontes-core/dyn-decode"]
