[package]
name = "brontes"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
brontes-core.workspace = true
brontes-macros.workspace = true
brontes-inspect.workspace = true
brontes-types.workspace = true
brontes-classifier.workspace = true
brontes-database.workspace = true
brontes-metrics.workspace = true
brontes-pricing.workspace = true
brontes-tracing.workspace = true
brontes-libmdbx = { workspace = true, features = ["read-tx-timeouts"] }

malachite.workspace = true
toml = "0.8.2"
indicatif.workspace = true

# filesystem
fs2 = "0.4.3"
fs_extra = "1.3.0"
filesize = "0.2.0"
tar = "0.4.41"
flate2 = "1.0.30"

# Async
tokio = { workspace = true }
async-scoped = { version = "0.7.1", features = ["use-tokio"] }
futures.workspace = true

reqwest.workspace = true
# Reth
reth-tasks.workspace = true
reth-rpc.workspace = true
reth-rpc-api.workspace = true
reth-rpc-types.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-network-api.workspace = true
reth-primitives.workspace = true
reth-db.workspace = true
reth-blockchain-tree.workspace = true
reth-beacon-consensus.workspace = true
#reth-revm.workspace = true
reth-interfaces.workspace = true

# Alloy
alloy-primitives.workspace = true
alloy-sol-macro = { workspace = true, features = ["json"] }
alloy-sol-types = { workspace = true, features = ["json"] }

alloy-provider.workspace = true
alloy-transport-http.workspace = true
alloy-transport.workspace = true
alloy-network.workspace = true
alloy-json-rpc.workspace = true
alloy-rpc-types.workspace = true
alloy-rpc-client.workspace = true

# tracing
tracing.workspace = true
tracing-subscriber.workspace = true
reth-tracing-ext.workspace = true
colored.workspace = true

# misc
eyre.workspace = true
dotenv.workspace = true
num_cpus.workspace = true
strum = { workspace = true, features = ["derive"] }
thiserror.workspace = true

# http/rpc
hyper.workspace = true

# cli
clap.workspace = true
# logging
indoc = "2"
rayon.workspace = true
cfg-if = "1.0.0"

# prometheus
metrics-process.workspace = true
prometheus = "0.13.4"
itertools.workspace = true
fdlimit = "0.3.0"
dhat = "0.3.3"

tikv-jemallocator = { version = "0.5.0", features = [
  "unprefixed_malloc_on_supported_platforms",
] }

[features]
default = [
  "brontes-core/default",
  "brontes-database/default",
  "brontes-classifier/default",
  "brontes-inspect/default",
  "jemalloc",
  "local-reth",
  "cex-dex-markout",
]

jemalloc = ["brontes-metrics/jemalloc"]
jemalloc-prof = ["jemalloc", "tikv-jemallocator/profiling"]
dhat-heap = []

sorella-server = ["local-reth", "local-clickhouse"]

cex-dex-markout = [
  "brontes-types/cex-dex-markout",
  "brontes-database/cex-dex-markout",
  "brontes-inspect/cex-dex-markout",
]


local-no-inserts = []

tests = [
  "brontes-core/tests",
  "brontes-database/tests",
  "brontes-classifier/tests",
  "brontes-inspect/tests",
  "brontes-pricing/tests",
]

local-reth = [
  "brontes-core/local-reth",
  "brontes-database/local-reth",
  "brontes-types/local-reth",
  "brontes-pricing/local-reth",
  "brontes-inspect/local-reth",
  "reth-tracing-ext/local-reth",
]

local-clickhouse = [
  "brontes-database/local-clickhouse",
  "brontes-core/local-clickhouse",
  "brontes-inspect/local-clickhouse",
  "brontes-classifier/local-clickhouse",
  "brontes-types/local-clickhouse",
]

uni-v3-ticks = ["brontes-pricing/uni-v3-ticks"]
dyn-decode = ["brontes-core/dyn-decode"]
