[package]
name = "bin"
version = "0.1.0"
edition = "2021"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# poirot
poirot-core.workspace = true
poirot-inspect.workspace = true
poirot-normalizer.workspace = true

# Async
tokio = { workspace = true, features = ["full", "tracing"] }
futures.workspace = true

# Reth
reth-tasks.workspace = true
reth-rpc.workspace = true
reth-rpc-api.workspace = true
reth-rpc-builder.workspace = true
reth-rpc-types.workspace = true
reth-provider.workspace = true
reth-transaction-pool.workspace = true
reth-network-api.workspace = true
reth-primitives.workspace = true
reth-db.workspace = true
reth-blockchain-tree.workspace = true
reth-beacon-consensus.workspace = true
reth-revm.workspace = true
reth-interfaces.workspace = true

# Alloy
alloy-sol-macro = { workspace = true, features = ["json"]}
alloy-sol-types = { workspace = true, features = ["json"]}

# logging
env_logger.workspace = true
log.workspace = true

# tracing
tracing.workspace = true
tracing-subscriber.workspace = true
reth-tracing.workspace = true
colored.workspace = true

# prometheus
metrics-exporter-prometheus.workspace = true
metrics-util.workspace = true
metrics-process.workspace = true

# misc
eyre.workspace = true

# http/rpc
hyper.workspace = true


[build-dependencies]
tokio.workspace = true
clickhouse = { git = "https://github.com/SorellaLabs/clickhouse.rs" }
hyper.workspace = true
hyper-tls = "0.5.0"
serde.workspace = true
serde_json.workspace = true
alloy-etherscan.workspace = true
ethers-core.workspace = true
phf = { version = "0.11.1", default-features = false }
phf_codegen = "0.11.1"
dotenv = "0.15.0"
