name: Bug Report
description: Create a bug report
labels: ["C-bug", "S-needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.

  - type: textarea
    id: what-happened
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.

        If the bug is in a crate you are using (i.e. you are not running the standard `brontes` binary) please mention that as well.
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to reproduce
      description: Please provide any steps you think might be relevant to reproduce the bug.
      placeholder: |
        Steps to reproduce:

        1. Start '...'
        2. Then '...'
        3. Check '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Brontes logs
      description: If applicable, please provide brontes logs leading up to the bug.
      render: text
    validations:
      required: false
  - type: dropdown
    id: platform
    attributes:
      label: Platform(s)
      description: What platform(s) did this occur on?
      multiple: true
      options:
        - Linux (x86)
        - Linux (ARM)
        - Mac (Intel)
        - Mac (Apple Silicon)
        - Windows (x86)
        - Windows (ARM)
    validations:
      required: true
  - type: input
    id: brontes-version
    attributes:
      label: What version/commit are you on?
      description: This can be obtained with `brontes --version`
    validations:
      required: true

  - type: input
    id: rust-nightly-version
    attributes:
      label: Rust Nightly Version
      description: Please specify the version of Rust nightly you are using (e.g., rustc 1.56.0-nightly (xxx 2021-08-xx)).
      placeholder: rustc 1.56.0-nightly (xxx 2021-08-xx)
    validations:
      required: true

  - type: input
    attributes:
      label: If you've built Brontes from source, provide the full command you used
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct]()
      options:
        - label: I agree to follow the Code of Conduct
          required: true
