name: Missed MEV Report
description: Use this form to report MEV bundles that brontes failed to classify.
labels: ["missed-mev", "S-needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an occurence of Mev we failed to classify. Please provide as much detail as possible to help us investigate.

  - type: textarea
    id: transaction-links
    attributes:
      label: Etherscan Links to Transactions
      description: Please provide Etherscan links for each transaction involved in the bundle.
      placeholder: |
        - https://etherscan.io/tx/0x...
        - https://etherscan.io/tx/0x...
    validations:
      required: true

  - type: textarea
    id: protocols-interacted
    attributes:
      label: Protocols Interacted With
      description: Specify the protocols that were interacted with for this bundle.
      placeholder: |
        - Protocol 1
        - Protocol 2
    validations:
      required: true

  - type: checkboxes
    id: protocols-supported
    attributes:
      label: All Protocols Supported?
      description: Indicate if all protocols were supported (i.e., if we had classifiers for these protocols).
      options:
        - label: Yes, all protocols were supported.
        - label: No, not all protocols were supported.
    validations:
      required: true

  - type: textarea
    id: protocols-needing-classifier
    attributes:
      label: Protocols Needing a Classifier (Optional)
      description: If not all protocols were supported, please list which protocols need to have a classifier developed.
      placeholder: |
        - Protocol 1
        - Protocol 2
    validations:
      required: false

  - type: textarea
    id: tokens-interacted
    attributes:
      label: Tokens Interacted With (Optional)
      description: List any tokens that were interacted with during the bundle (optional).
      placeholder: |
        - Token 1
        - Token 2
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](LINK_TO_CODE_OF_CONDUCT).
      options:
        - label: I agree to follow the Code of Conduct.
          required: true
