CREATE TYPE SingleTokenType AS (
    address Hash256,
    symbol VARCHAR(20)
);

CREATE TYPE TokenPairType AS (
    token0 SingleTokenType,
    token1 SingleTokenType
);

CREATE TYPE profit_revenue_type AS (
    profit        Hash256,
    profit_amt    DOUBLE PRECISION,
    revenue       Hash256,
    revenue_amt   DOUBLE PRECISION
);

CREATE TABLE brontes.block_analysis
(
    block_number BIGINT NOT NULL,
    eth_price DOUBLE PRECISION NOT NULL, 

    -- all
    all_total_profit                DOUBLE PRECISION NOT NULL,
    all_total_revenue               DOUBLE PRECISION NOT NULL,
    all_bundle_count                BIGINT NOT NULL,
    all_average_profit_margin       DOUBLE PRECISION NOT NULL,
    all_top_searcher_profit         Hash256,
    all_top_searcher_profit_amt     DOUBLE PRECISION,
    all_top_searcher_revenue        Hash256,
    all_top_searcher_revenue_amt    DOUBLE PRECISION,
    all_searcher_count              BIGINT NOT NULL,
    all_top_fund_profit             Hash256,
    all_top_fund_profit_amt         DOUBLE PRECISION,
    all_top_fund_revenue            Hash256,
    all_top_fund_revenue_amt        DOUBLE PRECISION,
    all_fund_count                  BIGINT NOT NULL,
    all_most_arbed_pool_profit      Hash256,
    all_most_arbed_pool_profit_amt  DOUBLE PRECISION,
    all_most_arbed_pool_revenue     Hash256,
    all_most_arbed_pool_revenue_amt DOUBLE PRECISION,
    all_most_arbed_pair_profit      TokenPairType NOT NULL,
    all_most_arbed_pair_profit_amt  DOUBLE PRECISION,
    all_most_arbed_pair_revenue     TokenPairType NOT NULL,
    all_most_arbed_pair_revenue_amt DOUBLE PRECISION,
    all_most_arbed_dex_profit       Hash256,
    all_most_arbed_dex_profit_amt   DOUBLE PRECISION,
    all_most_arbed_dex_revenue      Hash256,
    all_most_arbed_dex_revenue_amt  DOUBLE PRECISION,
    all_biggest_arb_profit          Hash256,
    all_biggest_arb_profit_amt      DOUBLE PRECISION,
    all_biggest_arb_revenue         Hash256,
    all_biggest_arb_revenue_amt     DOUBLE PRECISION,

    -- atomic arb
    atomic_bundle_count                BIGINT NOT NULL,
    atomic_total_profit                DOUBLE PRECISION NOT NULL,
    atomic_total_revenue               DOUBLE PRECISION NOT NULL,
    atomic_average_profit_margin       DOUBLE PRECISION NOT NULL,
    atomic_top_searcher_profit         Hash256,
    atomic_top_searcher_profit_amt     DOUBLE PRECISION,
    atomic_top_searcher_revenue        Hash256,
    atomic_top_searcher_revenue_amt    DOUBLE PRECISION,
    atomic_searcher_eoa_all            profit_revenue_type[] NOT NULL,
    atomic_searcher_eoa_count          BIGINT NOT NULL,
    atomic_mev_contract_all            profit_revenue_type[] NOT NULL,
    atomic_mev_contract_count          BIGINT NOT NULL,
    atomic_top_fund_profit             Hash256,
    atomic_top_fund_profit_amt         DOUBLE PRECISION,
    atomic_top_fund_revenue            Hash256,
    atomic_top_fund_revenue_amt        DOUBLE PRECISION,
    atomic_fund_all                    profit_revenue_type[] NOT NULL,
    atomic_fund_count                  BIGINT NOT NULL,
    atomic_most_arbed_pool_profit      Hash256,
    atomic_most_arbed_pool_profit_amt  DOUBLE PRECISION,
    atomic_most_arbed_pool_revenue     Hash256,
    atomic_most_arbed_pool_revenue_amt DOUBLE PRECISION,
    atomic_most_arbed_pair_profit      TokenPairType NOT NULL,
    atomic_most_arbed_pair_profit_amt  DOUBLE PRECISION,
    atomic_most_arbed_pair_revenue     TokenPairType NOT NULL,
    atomic_most_arbed_pair_revenue_amt DOUBLE PRECISION,
    atomic_most_arbed_dex_profit       Hash256,
    atomic_most_arbed_dex_profit_amt   DOUBLE PRECISION,
    atomic_most_arbed_dex_revenue      Hash256,
    atomic_most_arbed_dex_revenue_amt  DOUBLE PRECISION,
    atomic_arbed_pool_all              profit_revenue_type[] NOT NULL,
    atomic_arbed_pair_all              profit_revenue_type[] NOT NULL,
    atomic_arbed_dex_all               profit_revenue_type[] NOT NULL,
    atomic_biggest_arb_profit          Hash256,
    atomic_biggest_arb_profit_amt      DOUBLE PRECISION,
    atomic_biggest_arb_revenue         Hash256,
    atomic_biggest_arb_revenue_amt     DOUBLE PRECISION,

    -- sandwich
    sandwich_bundle_count BIGINT NOT NULL,
    sandwich_total_profit                DOUBLE PRECISION NOT NULL,
    sandwich_total_revenue               DOUBLE PRECISION NOT NULL,
    sandwich_average_profit_margin       DOUBLE PRECISION NOT NULL,
    sandwich_top_searcher_profit         Hash256,
    sandwich_top_searcher_profit_amt     DOUBLE PRECISION,
    sandwich_top_searcher_revenue        Hash256,
    sandwich_top_searcher_revenue_amt    DOUBLE PRECISION,
    sandwich_searcher_eoa_all            profit_revenue_type[] NOT NULL,
    sandwich_searcher_eoa_count          BIGINT NOT NULL,
    sandwich_mev_contract_all            profit_revenue_type[] NOT NULL,
    sandwich_mev_contract_count          BIGINT NOT NULL,
    sandwich_top_fund_profit             Hash256,
    sandwich_top_fund_profit_amt         DOUBLE PRECISION,
    sandwich_top_fund_revenue            Hash256,
    sandwich_top_fund_revenue_amt        DOUBLE PRECISION,
    sandwich_fund_all                    profit_revenue_type[] NOT NULL,
    sandwich_fund_count                  BIGINT NOT NULL,
    sandwich_most_arbed_pool_profit      Hash256,
    sandwich_most_arbed_pool_profit_amt  DOUBLE PRECISION,
    sandwich_most_arbed_pool_revenue     Hash256,
    sandwich_most_arbed_pool_revenue_amt DOUBLE PRECISION,
    sandwich_most_arbed_pair_profit      TokenPairType NOT NULL,
    sandwich_most_arbed_pair_profit_amt  DOUBLE PRECISION,
    sandwich_most_arbed_pair_revenue     TokenPairType NOT NULL,
    sandwich_most_arbed_pair_revenue_amt DOUBLE PRECISION,
    sandwich_most_arbed_dex_profit       Hash256,
    sandwich_most_arbed_dex_profit_amt   DOUBLE PRECISION,
    sandwich_most_arbed_dex_revenue      Hash256,
    sandwich_most_arbed_dex_revenue_amt  DOUBLE PRECISION,
    sandwich_arbed_pool_all              profit_revenue_type[] NOT NULL,
    sandwich_arbed_pair_all              profit_revenue_type[] NOT NULL,
    sandwich_arbed_dex_all               profit_revenue_type[] NOT NULL,
    sandwich_biggest_arb_profit          Hash256,
    sandwich_biggest_arb_profit_amt      DOUBLE PRECISION,
    sandwich_biggest_arb_revenue         Hash256,
    sandwich_biggest_arb_revenue_amt     DOUBLE PRECISION,

    -- jit
    jit_bundle_count                BIGINT NOT NULL,
    jit_total_profit                DOUBLE PRECISION NOT NULL,
    jit_total_revenue               DOUBLE PRECISION NOT NULL,
    jit_average_profit_margin       DOUBLE PRECISION NOT NULL,
    jit_top_searcher_profit         Hash256,
    jit_top_searcher_profit_amt     DOUBLE PRECISION,
    jit_top_searcher_revenue        Hash256,
    jit_top_searcher_revenue_amt    DOUBLE PRECISION,
    jit_searcher_eoa_all            profit_revenue_type[] NOT NULL,
    jit_searcher_eoa_count          BIGINT NOT NULL,
    jit_mev_contract_all            profit_revenue_type[] NOT NULL,
    jit_mev_contract_count          BIGINT NOT NULL,
    jit_top_fund_profit             Hash256,
    jit_top_fund_profit_amt         DOUBLE PRECISION,
    jit_top_fund_revenue            Hash256,
    jit_top_fund_revenue_amt        DOUBLE PRECISION,
    jit_fund_all                    profit_revenue_type[] NOT NULL,
    jit_fund_count                  BIGINT NOT NULL,
    jit_most_arbed_pool_profit      Hash256,
    jit_most_arbed_pool_profit_amt  DOUBLE PRECISION,
    jit_most_arbed_pool_revenue     Hash256,
    jit_most_arbed_pool_revenue_amt DOUBLE PRECISION,
    jit_most_arbed_pair_profit      TokenPairType NOT NULL,
    jit_most_arbed_pair_profit_amt  DOUBLE PRECISION,
    jit_most_arbed_pair_revenue     TokenPairType NOT NULL,
    jit_most_arbed_pair_revenue_amt DOUBLE PRECISION,
    jit_most_arbed_dex_profit       Hash256,
    jit_most_arbed_dex_profit_amt   DOUBLE PRECISION,
    jit_most_arbed_dex_revenue      Hash256,
    jit_most_arbed_dex_revenue_amt  DOUBLE PRECISION,
    jit_arbed_pool_all              profit_revenue_type[] NOT NULL,
    jit_arbed_pair_all              profit_revenue_type[] NOT NULL,
    jit_arbed_dex_all               profit_revenue_type[] NOT NULL,
    jit_biggest_arb_profit          Hash256,
    jit_biggest_arb_profit_amt      DOUBLE PRECISION,
    jit_biggest_arb_revenue         Hash256,
    jit_biggest_arb_revenue_amt     DOUBLE PRECISION,

    -- jit sandwich
    jit_sandwich_bundle_count                BIGINT NOT NULL,
    jit_sandwich_total_profit                DOUBLE PRECISION NOT NULL,
    jit_sandwich_total_revenue               DOUBLE PRECISION NOT NULL,
    jit_sandwich_average_profit_margin       DOUBLE PRECISION NOT NULL,
    jit_sandwich_top_searcher_profit         Hash256,
    jit_sandwich_top_searcher_profit_amt     DOUBLE PRECISION,
    jit_sandwich_top_searcher_revenue        Hash256,
    jit_sandwich_top_searcher_revenue_amt    DOUBLE PRECISION,
    jit_sandwich_searcher_eoa_all            profit_revenue_type[] NOT NULL,
    jit_sandwich_searcher_eoa_count          BIGINT NOT NULL,
    jit_sandwich_mev_contract_all            profit_revenue_type[] NOT NULL,
    jit_sandwich_mev_contract_count          BIGINT NOT NULL,
    jit_sandwich_top_fund_profit             Hash256,
    jit_sandwich_top_fund_profit_amt         DOUBLE PRECISION,
    jit_sandwich_top_fund_revenue            Hash256,
    jit_sandwich_top_fund_revenue_amt        DOUBLE PRECISION,
    jit_sandwich_fund_all                    profit_revenue_type[] NOT NULL,
    jit_sandwich_fund_count                  BIGINT NOT NULL,
    jit_sandwich_most_arbed_pool_profit      Hash256,
    jit_sandwich_most_arbed_pool_profit_amt  DOUBLE PRECISION,
    jit_sandwich_most_arbed_pool_revenue     Hash256,
    jit_sandwich_most_arbed_pool_revenue_amt DOUBLE PRECISION,
    jit_sandwich_most_arbed_pair_profit      TokenPairType NOT NULL,
    jit_sandwich_most_arbed_pair_profit_amt  DOUBLE PRECISION,
    jit_sandwich_most_arbed_pair_revenue     TokenPairType NOT NULL,
    jit_sandwich_most_arbed_pair_revenue_amt DOUBLE PRECISION,
    jit_sandwich_most_arbed_dex_profit       Hash256,
    jit_sandwich_most_arbed_dex_profit_amt   DOUBLE PRECISION,
    jit_sandwich_most_arbed_dex_revenue      Hash256,
    jit_sandwich_most_arbed_dex_revenue_amt  DOUBLE PRECISION,
    jit_sandwich_arbed_pool_all              profit_revenue_type[] NOT NULL,
    jit_sandwich_arbed_pair_all              profit_revenue_type[] NOT NULL,
    jit_sandwich_arbed_dex_all               profit_revenue_type[] NOT NULL,
    jit_sandwich_biggest_arb_profit          Hash256,
    jit_sandwich_biggest_arb_profit_amt      DOUBLE PRECISION,
    jit_sandwich_biggest_arb_revenue         Hash256,
    jit_sandwich_biggest_arb_revenue_amt     DOUBLE PRECISION,

    -- cex_dex
    cex_dex_bundle_count                BIGINT NOT NULL,
    cex_dex_total_profit                DOUBLE PRECISION NOT NULL,
    cex_dex_total_revenue               DOUBLE PRECISION NOT NULL,
    cex_dex_average_profit_margin       DOUBLE PRECISION NOT NULL,
    cex_dex_top_searcher_profit         Hash256,
    cex_dex_top_searcher_profit_amt     DOUBLE PRECISION,
    cex_dex_top_searcher_revenue        Hash256,
    cex_dex_top_searcher_revenue_amt    DOUBLE PRECISION,
    cex_dex_searcher_eoa_all            profit_revenue_type[] NOT NULL,
    cex_dex_searcher_eoa_count          BIGINT NOT NULL,
    cex_dex_mev_contract_all            profit_revenue_type[] NOT NULL,
    cex_dex_mev_contract_count          BIGINT NOT NULL,
    cex_dex_top_fund_profit             Hash256,
    cex_dex_top_fund_profit_amt         DOUBLE PRECISION,
    cex_dex_top_fund_revenue            Hash256,
    cex_dex_top_fund_revenue_amt        DOUBLE PRECISION,
    cex_dex_fund_all                    profit_revenue_type[] NOT NULL,
    cex_dex_fund_count                  BIGINT NOT NULL,
    cex_dex_most_arbed_pool_profit      Hash256,
    cex_dex_most_arbed_pool_profit_amt  DOUBLE PRECISION,
    cex_dex_most_arbed_pool_revenue     Hash256,
    cex_dex_most_arbed_pool_revenue_amt DOUBLE PRECISION,
    cex_dex_most_arbed_pair_profit      TokenPairType NOT NULL,
    cex_dex_most_arbed_pair_profit_amt  DOUBLE PRECISION,
    cex_dex_most_arbed_pair_revenue     TokenPairType NOT NULL,
    cex_dex_most_arbed_pair_revenue_amt DOUBLE PRECISION,
    cex_dex_most_arbed_dex_profit       Hash256,
    cex_dex_most_arbed_dex_profit_amt   DOUBLE PRECISION,
    cex_dex_most_arbed_dex_revenue      Hash256,
    cex_dex_most_arbed_dex_revenue_amt  DOUBLE PRECISION,
    cex_dex_arbed_pool_all              profit_revenue_type[] NOT NULL,
    cex_dex_arbed_pair_all              profit_revenue_type[] NOT NULL,
    cex_dex_arbed_dex_all               profit_revenue_type[] NOT NULL,
    cex_dex_biggest_arb_profit          Hash256,
    cex_dex_biggest_arb_profit_amt      DOUBLE PRECISION,
    cex_dex_biggest_arb_revenue         Hash256,
    cex_dex_biggest_arb_revenue_amt     DOUBLE PRECISION,

    -- liquidation
    liquidation_bundle_count                BIGINT NOT NULL,
    liquidation_total_profit                DOUBLE PRECISION NOT NULL,
    liquidation_total_revenue               DOUBLE PRECISION NOT NULL,
    liquidation_average_profit_margin       DOUBLE PRECISION NOT NULL,
    liquidation_top_searcher_profit         Hash256,
    liquidation_top_searcher_profit_amt     DOUBLE PRECISION,
    liquidation_top_searcher_revenue        Hash256,
    liquidation_top_searcher_revenue_amt    DOUBLE PRECISION,
    liquidation_searcher_eoa_all            profit_revenue_type[] NOT NULL,
    liquidation_searcher_eoa_count          BIGINT NOT NULL,
    liquidation_mev_contract_all            profit_revenue_type[] NOT NULL,
    liquidation_mev_contract_count          BIGINT NOT NULL,
    liquidation_top_fund_profit             Hash256,
    liquidation_top_fund_profit_amt         DOUBLE PRECISION,
    liquidation_top_fund_revenue            Hash256,
    liquidation_top_fund_revenue_amt        DOUBLE PRECISION,
    liquidation_fund_all                    profit_revenue_type[] NOT NULL,
    liquidation_fund_count                  BIGINT NOT NULL,
    most_liquidated_token_revenue           SingleTokenType NOT NULL,
    most_liquidated_token_revenue_amt       DOUBLE PRECISION,
    most_liquidated_token_profit            SingleTokenType NOT NULL,
    most_liquidated_token_profit_amt        DOUBLE PRECISION,
    liquidated_tokens                       profit_revenue_type[] NOT NULL,
    liquidated_biggest_arb_profit           Hash256,
    liquidated_biggest_arb_profit_amt       DOUBLE PRECISION,
    liquidated_biggest_arb_revenue          Hash256,
    liquidated_biggest_arb_revenue_amt      DOUBLE PRECISION,
    total_usd_liquidated                    DOUBLE PRECISION NOT NULL,

    builder_profit_usd     DOUBLE PRECISION NOT NULL,
    builder_profit_eth     DOUBLE PRECISION NOT NULL,
    builder_revenue_usd    DOUBLE PRECISION NOT NULL,
    builder_revenue_eth    DOUBLE PRECISION NOT NULL,
    builder_mev_profit_usd DOUBLE PRECISION NOT NULL,
    builder_mev_profit_eth DOUBLE PRECISION NOT NULL,
    builder_name           TEXT,
    builder_address        Hash256,
    proposer_profit_usd    DOUBLE PRECISION,
    proposer_profit_eth    DOUBLE PRECISION,
    
    run_id BIGINT NOT NULL,
    PRIMARY KEY (block_number)
);