/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetDeliveredPayloads200ResponseInnerAllOf {
    #[serde(rename = "block_number", skip_serializing_if = "Option::is_none")]
    pub block_number: Option<String>,
    #[serde(rename = "num_tx", skip_serializing_if = "Option::is_none")]
    pub num_tx:       Option<String>,
}

impl GetDeliveredPayloads200ResponseInnerAllOf {
    pub fn new() -> GetDeliveredPayloads200ResponseInnerAllOf {
        GetDeliveredPayloads200ResponseInnerAllOf { block_number: None, num_tx: None }
    }
}
