/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetValidators200ResponseInnerEntryMessage : The `ValidatorRegistration`
/// object from the Builder API specification.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetValidators200ResponseInnerEntryMessage {
    /// Address to receive fees from the block.
    #[serde(rename = "fee_recipient", skip_serializing_if = "Option::is_none")]
    pub fee_recipient: Option<String>,
    /// Preferred gas limit of validator.
    #[serde(rename = "gas_limit", skip_serializing_if = "Option::is_none")]
    pub gas_limit:     Option<String>,
    /// Unix timestamp of registration.
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp:     Option<String>,
    /// BLS public key of validator.
    #[serde(rename = "pubkey", skip_serializing_if = "Option::is_none")]
    pub pubkey:        Option<String>,
}

impl GetValidators200ResponseInnerEntryMessage {
    /// The `ValidatorRegistration` object from the Builder API specification.
    pub fn new() -> GetValidators200ResponseInnerEntryMessage {
        GetValidators200ResponseInnerEntryMessage {
            fee_recipient: None,
            gas_limit:     None,
            timestamp:     None,
            pubkey:        None,
        }
    }
}
