/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetReceivedBids200ResponseInnerAllOf {
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp:    Option<String>,
    #[serde(rename = "timestamp_ms", skip_serializing_if = "Option::is_none")]
    pub timestamp_ms: Option<String>,
}

impl GetReceivedBids200ResponseInnerAllOf {
    pub fn new() -> GetReceivedBids200ResponseInnerAllOf {
        GetReceivedBids200ResponseInnerAllOf { timestamp: None, timestamp_ms: None }
    }
}
