/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetReceivedBids200ResponseInner {
    #[serde(rename = "slot", skip_serializing_if = "Option::is_none")]
    pub slot:                   Option<String>,
    #[serde(rename = "parent_hash", skip_serializing_if = "Option::is_none")]
    pub parent_hash:            Option<String>,
    #[serde(rename = "block_hash", skip_serializing_if = "Option::is_none")]
    pub block_hash:             Option<String>,
    /// The validator's BLS public key, uniquely identifying them. _48-bytes,
    /// hex encoded with 0x prefix, case insensitive._
    #[serde(rename = "builder_pubkey", skip_serializing_if = "Option::is_none")]
    pub builder_pubkey:         Option<String>,
    /// An address on the execution (Ethereum 1) network.
    #[serde(rename = "proposer_fee_recipient", skip_serializing_if = "Option::is_none")]
    pub proposer_fee_recipient: Option<String>,
    #[serde(rename = "gas_limit", skip_serializing_if = "Option::is_none")]
    pub gas_limit:              Option<String>,
    #[serde(rename = "gas_used", skip_serializing_if = "Option::is_none")]
    pub gas_used:               Option<String>,
    #[serde(rename = "value", skip_serializing_if = "Option::is_none")]
    pub value:                  Option<String>,
    #[serde(rename = "block_number", skip_serializing_if = "Option::is_none")]
    pub block_number:           Option<String>,
    #[serde(rename = "num_tx", skip_serializing_if = "Option::is_none")]
    pub num_tx:                 Option<String>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    pub timestamp:              Option<String>,
    #[serde(rename = "timestamp_ms", skip_serializing_if = "Option::is_none")]
    pub timestamp_ms:           Option<String>
}

impl GetReceivedBids200ResponseInner {
    pub fn new() -> GetReceivedBids200ResponseInner {
        GetReceivedBids200ResponseInner {
            slot:                   None,
            parent_hash:            None,
            block_hash:             None,
            builder_pubkey:         None,
            proposer_fee_recipient: None,
            gas_limit:              None,
            gas_used:               None,
            value:                  None,
            block_number:           None,
            num_tx:                 None,
            timestamp:              None,
            timestamp_ms:           None
        }
    }
}
