/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

/// GetValidators200ResponseInnerEntry : The `SignedValidatorRegistration`
/// object from the Builder API specification.

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct GetValidators200ResponseInnerEntry {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message:   Option<Box<crate::models::GetValidators200ResponseInnerEntryMessage>>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>
}

impl GetValidators200ResponseInnerEntry {
    /// The `SignedValidatorRegistration` object from the Builder API
    /// specification.
    pub fn new() -> GetValidators200ResponseInnerEntry {
        GetValidators200ResponseInnerEntry { message: None, signature: None }
    }
}
