/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

/// OrderBy : Sort results in either ascending or descending values.  * `-value`
/// - descending value (highest value first)  * `value` - ascending value
/// (lowest value first)

/// Sort results in either ascending or descending values.  * `-value` -
/// descending value (highest value first)  * `value` - ascending value (lowest
/// value first)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OrderBy {
    #[serde(rename = "-value")]
    NegValue,
    #[serde(rename = "value")]
    Value
}

#[allow(clippy::to_string_trait_impl)]
impl ToString for OrderBy {
    fn to_string(&self) -> String {
        match self {
            Self::NegValue => String::from("-value"),
            Self::Value => String::from("value")
        }
    }
}

impl Default for OrderBy {
    fn default() -> OrderBy {
        Self::Value
    }
}
