/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitBlock200Response {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message:   Option<Box<crate::models::SubmitBlock200ResponseMessage>>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>,
}

impl SubmitBlock200Response {
    pub fn new() -> SubmitBlock200Response {
        SubmitBlock200Response { message: None, signature: None }
    }
}
