/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitBlockRequest {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message:           Option<Box<crate::models::SubmitBlockRequestMessage>>,
    #[serde(rename = "execution_payload", skip_serializing_if = "Option::is_none")]
    pub execution_payload: Option<Box<crate::models::SubmitBlockRequestExecutionPayload>>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature:         Option<String>
}

impl SubmitBlockRequest {
    pub fn new() -> SubmitBlockRequest {
        SubmitBlockRequest { message: None, execution_payload: None, signature: None }
    }
}
