/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitBlockRequestExecutionPayloadOneOf1AllOf1WithdrawalsInner {
    /// The index of the withdrawal.
    #[serde(rename = "index", skip_serializing_if = "Option::is_none")]
    pub index:           Option<String>,
    /// The index of the withdrawing validator.
    #[serde(rename = "validator_index", skip_serializing_if = "Option::is_none")]
    pub validator_index: Option<String>,
    /// The address to which the withdrawal is credited.
    #[serde(rename = "address", skip_serializing_if = "Option::is_none")]
    pub address:         Option<String>,
    /// The value withdrawn (gwei).
    #[serde(rename = "amount", skip_serializing_if = "Option::is_none")]
    pub amount:          Option<String>,
}

impl SubmitBlockRequestExecutionPayloadOneOf1AllOf1WithdrawalsInner {
    pub fn new() -> SubmitBlockRequestExecutionPayloadOneOf1AllOf1WithdrawalsInner {
        SubmitBlockRequestExecutionPayloadOneOf1AllOf1WithdrawalsInner {
            index:           None,
            validator_index: None,
            address:         None,
            amount:          None,
        }
    }
}
