/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitBlock200ResponseMessage {
    #[serde(rename = "receive_timestamp", skip_serializing_if = "Option::is_none")]
    pub receive_timestamp: Option<String>,
    #[serde(rename = "bid_trace", skip_serializing_if = "Option::is_none")]
    pub bid_trace:         Option<Box<crate::models::SubmitBlockRequestMessage>>
}

impl SubmitBlock200ResponseMessage {
    pub fn new() -> SubmitBlock200ResponseMessage {
        SubmitBlock200ResponseMessage { receive_timestamp: None, bid_trace: None }
    }
}
