/*
 * Relay API
 *
 * API specification for MEV-Boost PBS relays.
 *
 * The version of the OpenAPI document: dev
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SubmitBlockResponse {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message:   Option<Box<crate::models::SubmitBlock200ResponseMessage>>,
    #[serde(rename = "signature", skip_serializing_if = "Option::is_none")]
    pub signature: Option<String>
}

impl SubmitBlockResponse {
    pub fn new() -> SubmitBlockResponse {
        SubmitBlockResponse { message: None, signature: None }
    }
}
