#!/bin/sh
rustc -L ./target/debug/ -L dependency=./target/debug/deps/ --extern alloy_sol_macro=./target/debug/deps/liballoy_sol_macro-a58091a95dbdff94.so --extern alloy_json_abi=./target/debug/deps/liballoy_json_abi-eee0a87b1916f8b5.rlib --extern alloy_primitives=./target/debug/deps/liballoy_primitives-f980c0218e29ce68.rlib --extern alloy_sol_types=./target/debug/deps/liballoy_sol_types-4c87198cb969083d.rlib --extern alloy_sol_type_parser=./target/debug/deps/liballoy_sol_type_parser-4e706d9243f13644.rlib --extern ruint=./target/debug/deps/libruint-3dada850bd72bb20.rlib --extern arbitrary=./target/debug/deps/libarbitrary-5631f52023221966.rlib --extern derive_arbitrary=./target/debug/deps/libderive_arbitrary-d27f99037ac777d1.so --extern primitive_types=./target/debug/deps/libprimitive_types-154ebff147e3f8ae.rlib --crate-type dylib -C inline-threshold=25 ./dylib-bindings/src/test_sol.rs

# /home/will/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name brontes_classifier --edition=2021 crates/brontes-classifier/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifac
# ts,future-incompat --diagnostic-width=253 --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C codegen-units=16 -C debuginfo=2 --cfg 'feature="brontes-core"' --cfg 'feature="default"' --cfg 'feature="reth-tracing"' --cfg 'feature="tests
# "' -C metadata=bcbd69af700f12c3 -C extra-filename=-bcbd69af700f12c3 --out-dir /home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps -C incremental=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/incremental -L dependency=/home/will/
# ghq/github.com/SorellaLabs/brontes/target/debug/deps --extern alloy_sol_macro=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/liballoy_sol_macro-a58091a95dbdff94.so --extern alloy_sol_types=/home/will/ghq/github.com/SorellaLabs/brontes/t
# arget/debug/deps/liballoy_sol_types-4c87198cb969083d.rmeta --extern brontes_core=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libbrontes_core-460157b3d5ee6870.rmeta --extern brontes_database=/home/will/ghq/github.com/SorellaLabs/bront
# es/target/debug/deps/libbrontes_database-8bf7f699e1050b43.rmeta --extern brontes_macros=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libbrontes_macros-1458f3bfbbe29e05.so --extern brontes_types=/home/will/ghq/github.com/SorellaLabs/br
# ontes/target/debug/deps/libbrontes_types-de1b746f5b973e56.rmeta --extern hex_literal=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libhex_literal-4195800cc562ec37.rmeta --extern itertools=/home/will/ghq/github.com/SorellaLabs/brontes/t
# arget/debug/deps/libitertools-93af5810bb4a9065.rmeta --extern lazy_static=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/liblazy_static-d3a2ac0ae80c78b3.rmeta --extern malachite=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug
# /deps/libmalachite-faae11131c2fc1c7.rmeta --extern once_cell=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libonce_cell-75570efb2f95e967.rmeta --extern parking_lot=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libpark
# ing_lot-4a2f12d12d120fd4.rmeta --extern paste=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libpaste-fcfc1e8685b6531b.so --extern phf=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libphf-8248e14107448113.rmeta --exter
# n rayon=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/librayon-fb4527a3f994642b.rmeta --extern reth_primitives=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libreth_primitives-4b083610eaa4e991.rmeta --extern reth_rpc_
# types=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libreth_rpc_types-f40d1b7a5c3be26b.rmeta --extern reth_tracing=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libreth_tracing-36b931b7c86c35b2.rmeta --extern serde_js
# on=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libserde_json-a889da6fa7cc50ce.rmeta --extern tracing=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/deps/libtracing-dff14967882f3f31.rmeta -L native=/home/will/ghq/github.co
# m/SorellaLabs/brontes/target/debug/build/ring-21cc5ad3c49da439/out -L native=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/build/c-kzg-31be2969998b343a/out -L native=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/build/blst-8528
# 96b16c05dea9/out -L native=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/build/c-kzg-b30fff6b130fdb19/out -L native=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/build/secp256k1-sys-a39681811229ce4b/out -L native=/home/will/ghq
# /github.com/SorellaLabs/brontes/target/debug/build/zstd-sys-01d9f0e60fd8e64c/out -L native=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/build/clickhouse-rs-cityhash-sys-1b9497a99f7781cd/out -L native=/home/will/ghq/github.com/SorellaLabs/b
# rontes/target/debug/build/lz4-sys-f90e1453660bb1f1/out -L native=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/build/ring-f5ca267af2fe96cb/out -L native=/home/will/ghq/github.com/SorellaLabs/brontes/target/debug/build/reth-mdbx-sys-483267c3
# e7fcdeef/out`
