{
 "title": "Brontes",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Active Inspector by range",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "range_active_inspector_processing",
     "legendFormat": "{{range_id}}"
    }
   ]
  },
  {
   "title": "Pending Trees ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "range_pending_trees", "legendFormat": "{{range_id}}" }
   ]
  },
  {
   "title": "Warn Logs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "brontes_log_count_with_target{level=\"WARN\"}",
     "legendFormat": "{{target}}"
    }
   ]
  },
  {
   "title": "Pricing That Needs More Data",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "count(dex_pricing_needs_more_data == 1)",
     "legendFormat": "__auto"
    },
    { "expr": "dex_pricing_needs_more_data", "legendFormat": "{{range_id}}" }
   ]
  },
  {
   "title": "Alive Inspectors (has some amount of processing occuring)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "count ((range_active_inspector_processing + (rate(dex_pricing_range_poll_rate[3m]) > 0 + rate(range_poll_rate[3m]) > 0)) > 0)",
     "legendFormat": "count ((range_active_inspector_processing + (rate(dex_pricing_range_poll_rate[3m]) > 0 + rate(range_poll_rate[3m]) > 0)) > 0)"
    }
   ]
  },
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Jemalloc Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "brontes_jemalloc_active", "legendFormat": "{{__name__}}" },
    { "expr": "brontes_jemalloc_allocated", "legendFormat": "{{__name__}}" },
    { "expr": "brontes_jemalloc_mapped", "legendFormat": "{{__name__}}" },
    { "expr": "brontes_jemalloc_metadata", "legendFormat": "{{__name__}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(rate(brontes_process_cpu_seconds_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "IO",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(rate(brontes_io_read_bytes[1m]))",
     "legendFormat": "Read Bytes"
    },
    {
     "expr": "avg(rate(brontes_io_write_bytes[1m]))",
     "legendFormat": "Write Bytes"
    }
   ]
  },
  { "title": "State Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Block Tracing Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(block_tracing_throughput_sum[3m])) / sum(rate(block_tracing_throughput_count[3m]))",
     "legendFormat": "Average"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(block_tracing_throughput_bucket[5m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(block_tracing_throughput_bucket[5m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(block_tracing_throughput_bucket[5m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(block_tracing_throughput_bucket[5m])) by (le))",
     "legendFormat": "50"
    }
   ]
  },
  {
   "title": "Tree Builder Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tree_builder_throughput_bucket[5m])) by (le))",
     "legendFormat": "99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(tree_builder_throughput_bucket[5m])) by (le))",
     "legendFormat": "95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(tree_builder_throughput_bucket[5m])) by (le))",
     "legendFormat": "90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(tree_builder_throughput_bucket[5m])) by (le))",
     "legendFormat": "75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(tree_builder_throughput_bucket[5m])) by (le))",
     "legendFormat": "50"
    },
    {
     "expr": "sum(rate(tree_builder_throughput_sum[3m])) / sum(rate(tree_builder_throughput_count[3m]))",
     "legendFormat": "avg"
    }
   ]
  },
  {
   "title": "Top vs Bottom block Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(bottomk(25, rate(block_tracing_throughput_sum[3m]) / rate(block_tracing_throughput_count[3m])))",
     "legendFormat": "bottom"
    },
    {
     "expr": "avg(topk(25, rate(block_tracing_throughput_sum[3m]) / rate(block_tracing_throughput_count[3m])))",
     "legendFormat": "top"
    }
   ]
  },
  {
   "title": "Top vs Bottom Tree builder ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(bottomk(25, rate(tree_builder_throughput_sum[3m]) / rate(tree_builder_throughput_count[3m])))",
     "legendFormat": "bottom"
    },
    {
     "expr": "avg(topk(25, rate(tree_builder_throughput_sum[3m]) / rate(tree_builder_throughput_count[3m])))",
     "legendFormat": "top"
    }
   ]
  },
  {
   "title": "Block Tracing Blocks Per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(block_tracing_throughput_count[3m])",
     "legendFormat": "{{range_id}}"
    }
   ]
  },
  {
   "title": " Tree builder blocks per sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "rate(tree_builder_throughput_count[3m])",
     "legendFormat": "{{range_id}}"
    }
   ]
  },
  { "title": "Async Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 } },
  {
   "title": "range poll rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "targets": [
    { "expr": "rate(range_poll_rate[5m])", "legendFormat": "{{range_id}}" }
   ]
  },
  {
   "title": "polls per sec dex pricing",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "rate(dex_pricing_range_poll_rate[5m])",
     "legendFormat": "{{range_id}}"
    }
   ]
  },
  {
   "title": "range poll rate 25",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "avg(bottomk(25,rate(range_poll_rate[5m])))",
     "legendFormat": "Avg Poll Rate Bottom"
    },
    {
     "expr": "avg(topk(25,rate(range_poll_rate[5m])))",
     "legendFormat": "Avg Poll Rate Top"
    }
   ]
  },
  {
   "title": "polls dex pricing rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "targets": [
    {
     "expr": "avg(topk(25, rate(dex_pricing_range_poll_rate[5m])))",
     "legendFormat": "top 25 avg"
    },
    {
     "expr": "avg(bottomk(25, rate(dex_pricing_range_poll_rate[5m])))",
     "legendFormat": "bottom 25 avg"
    }
   ]
  },
  {
   "title": "Range Throughputs",
   "type": "gauge",
   "description": "The amount of ranges currently doing some amount of work",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count( rate(range_poll_rate[2m]) > 0)",
     "legendFormat": "Range"
    },
    {
     "expr": "count(rate(dex_pricing_range_poll_rate[2m]) > 0)",
     "legendFormat": "Dex Pricing"
    }
   ]
  },
  { "title": "Progress", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "Blocks per second 3m avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "targets": [
    {
     "expr": " rate(brontes_brontes_total_completed_blocks[3m])",
     "legendFormat": "blocks/sec"
    }
   ]
  },
  {
   "title": "Range progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "targets": [
    {
     "expr": "brontes_range_specific_completed_blocks",
     "legendFormat": "{{range_id}}"
    },
    {
     "expr": "brontes_range_specific_total_blocks{range_id=\"0\"}",
     "legendFormat": "Finished Line"
    }
   ]
  },
  {
   "title": "Completed blocks (inspector counter based)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "brontes_brontes_total_completed_blocks",
     "legendFormat": "completed blocks"
    }
   ]
  },
  {
   "title": "Brontes Average inspector processing time ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 100 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "brontes_brontes_processing_runtime_ms",
     "legendFormat": "quantile: {{quantile}}"
    },
    {
     "expr": "brontes_range_executor_processing_run_time_ms{quantile=\"0.95\"}",
     "legendFormat": "0.95q processing runtime"
    }
   ]
  },
  {
   "title": "Current Range Tasks Running",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brontes_brontes_running_ranges_running_ranges",
     "legendFormat": "Active Range Executors"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 108 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "brontes_log_count_with_target{level=\"ERROR\"}",
     "legendFormat": "{{level}}={{target}}"
    }
   ]
  },
  {
   "title": "full inspector tasks",
   "type": "timeseries",
   "description": "the amount of inspector tasks that are full and blocking the rest of the processing",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
   "targets": [
    {
     "expr": "count (range_active_inspector_processing > 4)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "runnin inspector tasks",
   "type": "timeseries",
   "description": "Inspectors that are processing something\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
   "targets": [
    {
     "expr": "count(range_active_inspector_processing > 0)",
     "legendFormat": "Total non zero"
    }
   ]
  },
  { "title": "Dex Pricing", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 124 } },
  {
   "title": "Bottom 25 throughput call spread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) rate(dex_pricing_function_call_count{function_name=\"poll_state_processing\"}[5m]))",
     "legendFormat": "poll_state_processing"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"pool_updates_no_pricing\"}[5m]),0.000001))",
     "legendFormat": "pool_updates_no_pricing"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"try_resolve_block\"}[5m]),0.0000001))",
     "legendFormat": "try_resolve_block"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"add subgraph\"}[5m]),0.00000001))",
     "legendFormat": "add subgraph"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"bad_state_requery\"}[5m]),0.00000001))",
     "legendFormat": "bad state query"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"on_pool_updates\"}[5m]),0.000000001))",
     "legendFormat": "on_pool_updates"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"pool_resolve\"}[5m]),0.0000000001))",
     "legendFormat": "pool resolve"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"rundown\"}[5m]),0.0000000001))",
     "legendFormat": "rundown"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"try_verify_subgraph\"}[5m]),0.00000000000001)) ",
     "legendFormat": "try verify subgraph"
    },
    {
     "expr": "avg((clamp_min(bottomk(25, rate(dex_pricing_range_processed_blocks[3m])),1) / clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"try_flush_out_pending_verification\"}[5m]),0.00000001))",
     "legendFormat": "try_flush_out_pending_verification"
    }
   ]
  },
  {
   "title": "Top 25 throughput call spread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"poll_state_processing\"}[5m]),0.0000000001))",
     "legendFormat": "poll_state_processing"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"pool_updates_no_pricing\"}[5m]),0.000000001))",
     "legendFormat": "pool_updates_no_pricing"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"try_resolve_block\"}[5m]),0.00000001))",
     "legendFormat": "try_resolve_block"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"add subgraph\"}[5m]),0.00000001))",
     "legendFormat": "add subgraph"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"bad_state_requery\"}[5m]),0.000000001))",
     "legendFormat": "bad state query"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"on_pool_updates\"}[5m]),0.000001))",
     "legendFormat": "on_pool_updates"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"pool_resolve\"}[5m]),0.00000001))",
     "legendFormat": "pool resolve"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"rundown\"}[5m]),0.000000001))",
     "legendFormat": "rundown"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"try_verify_subgraph\"}[5m]),0.0000001))",
     "legendFormat": "try verify subgraph"
    },
    {
     "expr": "avg((clamp_min(topk(25, rate(dex_pricing_range_processed_blocks[3m])),1) * clamp_min(rate(dex_pricing_range_processed_blocks[3m]),1)) * on(range_id) clamp_min(rate(dex_pricing_function_call_count{function_name=\"try_flush_out_pending_verification\"}[5m]),0.00000001))",
     "legendFormat": "try_flush_out_pending_verification"
    }
   ]
  },
  {
   "title": "dex pricing processing speed / sec ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "avg(bottomk(5, rate(dex_pricing_range_processed_blocks[1m])))",
     "legendFormat": "bottom 5 avg rate"
    },
    {
     "expr": "avg(topk(5, rate(dex_pricing_range_processed_blocks[1m])))",
     "legendFormat": "top 5 avg rate "
    }
   ]
  },
  {
   "title": "function call averge 1 second sum",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(function_name) (sum by(function_name) (rate(dex_pricing_function_call_count[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ranges < 0.25 blocks/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": " sum(count by(range_id) (rate(brontes_range_specific_completed_blocks[3m])  < 0.25))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Graph State And Loading",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "targets": [
    {
     "expr": "brontes_dex_pricing_state_load_queries",
     "legendFormat": "Active State load queries"
    },
    {
     "expr": "brontes_dex_pricing_active_state",
     "legendFormat": "Active Pool State"
    },
    {
     "expr": "brontes_dex_pricing_active_subgraphs",
     "legendFormat": "Active Subgraphs"
    }
   ]
  },
  {
   "title": "StateLoading Speed ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "brontes_dex_pricing_state_load_time_ms",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  { "title": "Inspector Perf", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 157 } },
  {
   "title": "All Inspectors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(mev_type, le) (rate(inspector_runtime_ms_bucket[5m])))",
     "legendFormat": "{{mev_type}}: 99"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(mev_type, le) (rate(inspector_runtime_ms_bucket[5m])))",
     "legendFormat": "{{mev_type}}: 95"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(mev_type, le) (rate(inspector_runtime_ms_bucket[5m])))",
     "legendFormat": "{{mev_type}}: 90"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(mev_type, le) (rate(inspector_runtime_ms_bucket[5m])))",
     "legendFormat": "{{mev_type}}: 75"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(mev_type, le) (rate(inspector_runtime_ms_bucket[5m])))",
     "legendFormat": "{{mev_type}}: 50"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(mev_type, le) (rate(inspector_runtime_ms_bucket[5m])))",
     "legendFormat": "{{mev_type}}: 25"
    }
   ]
  },
  {
   "title": "Atomic Speed Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"AtomicArb\"}[5m])))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"AtomicArb\"}[5m])))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"AtomicArb\"}[5m])))",
     "legendFormat": "0.90q"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"AtomicArb\"}[5m])))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"AtomicArb\"}[5m])))",
     "legendFormat": "0.25q"
    },
    {
     "expr": "rate(inspector_runtime_ms_sum{mev_type=\"AtomicArb\"}[5m]) / rate(inspector_runtime_ms_count{mev_type=\"AtomicArb\"}[5m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"AtomicArb\"}[5m])))",
     "legendFormat": "1"
    }
   ]
  },
  {
   "title": "Sandwich Speed Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 166 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Sandwich\"}[5m])))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Sandwich\"}[5m])))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Sandwich\"}[5m])))",
     "legendFormat": "0.90q"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Sandwich\"}[5m])))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Sandwich\"}[5m])))",
     "legendFormat": "0.25q"
    },
    {
     "expr": "rate(inspector_runtime_ms_sum{mev_type=\"Sandwich\"}[5m]) / rate(inspector_runtime_ms_count{mev_type=\"Sandwich\"}[5m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Sandwich\"}[5m])))",
     "legendFormat": "1q"
    }
   ]
  },
  {
   "title": "jit Speed Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Jit\"}[5m])))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Jit\"}[5m])))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Jit\"}[5m])))",
     "legendFormat": "0.90q"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Jit\"}[5m])))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Jit\"}[5m])))",
     "legendFormat": "0.25q"
    },
    {
     "expr": "rate(inspector_runtime_ms_sum{mev_type=\"Jit\"}[5m]) / rate(inspector_runtime_ms_count{mev_type=\"Jit\"}[5m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Jit\"}[5m])))",
     "legendFormat": "1q"
    }
   ]
  },
  {
   "title": "CexDex Speed Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 174 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"CexDex\"}[5m])))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"CexDex\"}[5m])))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"CexDex\"}[5m])))",
     "legendFormat": "0.90q"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"CexDex\"}[5m])))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"CexDex\"}[5m])))",
     "legendFormat": "0.25q"
    },
    {
     "expr": "rate(inspector_runtime_ms_sum{mev_type=\"CexDex\"}[5m]) / rate(inspector_runtime_ms_count{mev_type=\"CexDex\"}[5m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"CexDex\"}[5m])))",
     "legendFormat": "1q"
    }
   ]
  },
  {
   "title": "Cex Price Speed Volume Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(cex_dex_price_speed_bucket{type=\"volume\"}[3m])) by (le))",
     "legendFormat": "1q"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cex_dex_price_speed_bucket{type=\"volume\"}[3m])) by (le))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cex_dex_price_speed_bucket{type=\"volume\"}[3m])) by (le))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(cex_dex_price_speed_bucket{type=\"volume\"}[3m])) by (le))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0, sum(rate(cex_dex_price_speed_bucket{type=\"volume\"}[3m])) by (le))",
     "legendFormat": "0q"
    },
    {
     "expr": "rate(cex_dex_price_speed_sum{type=\"volume\"}[3m]) / rate(cex_dex_price_speed_count{type=\"volume\"}[3m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Cex Price Speed Window Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 182 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(cex_dex_price_speed_bucket{type=\"window\"}[3m])) by (le))",
     "legendFormat": "1q"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(cex_dex_price_speed_bucket{type=\"window\"}[3m])) by (le))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(cex_dex_price_speed_bucket{type=\"window\"}[3m])) by (le))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(cex_dex_price_speed_bucket{type=\"window\"}[3m])) by (le))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0, sum(rate(cex_dex_price_speed_bucket{type=\"window\"}[3m])) by (le))",
     "legendFormat": "0q"
    },
    {
     "expr": "rate(cex_dex_price_speed_sum{type=\"window\"}[3m]) / rate(cex_dex_price_speed_count{type=\"window\"}[3m])",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "SearcherTx Speed Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"SearcherTx\"}[5m])))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"SearcherTx\"}[5m])))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"SearcherTx\"}[5m])))",
     "legendFormat": "0.90q"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"SearcherTx\"}[5m])))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"SearcherTx\"}[5m])))",
     "legendFormat": "0.25q"
    },
    {
     "expr": "rate(inspector_runtime_ms_sum{mev_type=\"SearcherTx\"}[5m]) / rate(inspector_runtime_ms_count{mev_type=\"SearcherTx\"}[5m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"SearcherTx\"}[5m])))",
     "legendFormat": "1q"
    }
   ]
  },
  {
   "title": "Liquidation Speed Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 190 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Liquidation\"}[5m])))",
     "legendFormat": "0.99q"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Liquidation\"}[5m])))",
     "legendFormat": "0.95q"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Liquidation\"}[5m])))",
     "legendFormat": "0.90q"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Liquidation\"}[5m])))",
     "legendFormat": "0.5q"
    },
    {
     "expr": "histogram_quantile(0.25, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Liquidation\"}[5m])))",
     "legendFormat": "0.25q"
    },
    {
     "expr": "rate(inspector_runtime_ms_sum{mev_type=\"Liquidation\"}[5m]) / rate(inspector_runtime_ms_count{mev_type=\"Liquidation\"}[5m])",
     "legendFormat": "Avg"
    },
    {
     "expr": "histogram_quantile(1, sum by(le) (rate(inspector_runtime_ms_bucket{mev_type=\"Liquidation\"}[5m])))",
     "legendFormat": "1q"
    }
   ]
  },
  {
   "title": "Inspectors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 },
   "collapsed": true,
   "panels": [
    {
     "title": "Filtering Trigger CexDex",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 155 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "brontes_branch_filtering_trigger{mev_type=\"CexDex\"}",
       "legendFormat": "{{branch_name}}"
      }
     ]
    },
    {
     "title": "Filtering Trigger AtomicArb",
     "type": "piechart",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 155 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "brontes_branch_filtering_trigger{mev_type=\"AtomicArb\"}",
       "legendFormat": "{{branch_name}}"
      }
     ]
    },
    {
     "title": "100x profit mev",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 163 },
     "targets": [
      { "expr": "brontes_100x_profit", "legendFormat": "{{mev_type}}" }
     ]
    },
    {
     "title": "missing cex pairs",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 163 },
     "targets": [
      { "expr": "cex_pair_no_symbols > 250", "legendFormat": "{{token0}} / {{token1}}" }
     ]
    },
    {
     "title": "bad dex pricing pairs > 25",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
     "targets": [
      {
       "expr": "brontes_bad_dex_pricing > 25",
       "legendFormat": "{{mev_type}}-{{token0}}  /  {{token1}}"
      }
     ]
    }
   ]
  }
 ]
}