CREATE TABLE brontes.block_analysis ON CLUSTER eth_cluster0  
(
    `block_number` UInt64,
    `eth_price` Float64, 

    -- all
    `all_total_profit`                Float64,
    `all_total_revenue`               Float64,
    `all_bundle_count` UInt64,
    `all_average_profit_margin`       Float64,
    `all_top_searcher_profit`         Nullable(String),
    `all_top_searcher_profit_amt`     Nullable(Float64),
    `all_top_searcher_revenue`        Nullable(String),
    `all_top_searcher_revenue_amt`    Nullable(Float64),
    `all_searcher_count`              UInt64,
    `all_top_fund_profit`             Nullable(String),
    `all_top_fund_profit_amt`         Nullable(Float64),
    `all_top_fund_revenue`            Nullable(String),
    `all_top_fund_revenue_amt`        Nullable(Float64),
    `all_fund_count`                  UInt64,
    `all_most_arbed_pool_profit`      Nullable(String),
    `all_most_arbed_pool_profit_amt`  Nullable(Float64),
    `all_most_arbed_pool_revenue`     Nullable(String),
    `all_most_arbed_pool_revenue_amt` Nullable(Float64),
    `all_most_arbed_pair_profit`      Tuple(Tuple(String, String), Tuple(String, String)),
    `all_most_arbed_pair_profit_amt`  Nullable(Float64),
    `all_most_arbed_pair_revenue`     Tuple(Tuple(String, String), Tuple(String, String)),
    `all_most_arbed_pair_revenue_amt` Nullable(Float64),
    `all_most_arbed_dex_profit`       Nullable(String),
    `all_most_arbed_dex_profit_amt`   Nullable(Float64),
    `all_most_arbed_dex_revenue`      Nullable(String),
    `all_most_arbed_dex_revenue_amt`  Nullable(Float64),
    `all_biggest_arb_profit`          Nullable(String),
    `all_biggest_arb_profit_amt`      Nullable(Float64),
    `all_biggest_arb_revenue`         Nullable(String),
    `all_biggest_arb_revenue_amt`     Nullable(Float64),

    -- atomic arb
    `atomic_bundle_count` UInt64,
    `atomic_total_profit`                Float64,
    `atomic_total_revenue`               Float64,
    `atomic_average_profit_margin`       Float64,
    `atomic_top_searcher_profit`         Nullable(String),
    `atomic_top_searcher_profit_amt`     Nullable(Float64),
    `atomic_top_searcher_revenue`        Nullable(String),
    `atomic_top_searcher_revenue_amt`    Nullable(Float64),
    `atomic_searcher_eoa_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `atomic_searcher_eoa_count`              UInt64,
    `atomic_mev_contract_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `atomic_mev_contract_count`              UInt64,
    `atomic_top_fund_profit`             Nullable(String),
    `atomic_top_fund_profit_amt`         Nullable(Float64),
    `atomic_top_fund_revenue`            Nullable(String),
    `atomic_top_fund_revenue_amt`        Nullable(Float64),
    `atomic_fund_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `atomic_fund_count`                  UInt64,
    `atomic_most_arbed_pool_profit`      Nullable(String),
    `atomic_most_arbed_pool_profit_amt`  Nullable(Float64),
    `atomic_most_arbed_pool_revenue`     Nullable(String),
    `atomic_most_arbed_pool_revenue_amt` Nullable(Float64),
    `atomic_most_arbed_pair_profit`      Tuple(Tuple(String, String), Tuple(String, String)),
    `atomic_most_arbed_pair_profit_amt`  Nullable(Float64),
    `atomic_most_arbed_pair_revenue`     Tuple(Tuple(String, String), Tuple(String, String)),
    `atomic_most_arbed_pair_revenue_amt` Nullable(Float64),
    `atomic_most_arbed_dex_profit`       Nullable(String),
    `atomic_most_arbed_dex_profit_amt`   Nullable(Float64),
    `atomic_most_arbed_dex_revenue`      Nullable(String),
    `atomic_most_arbed_dex_revenue_amt`  Nullable(Float64),
    `atomic_arbed_pool_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `atomic_arbed_pair_all` Nested (
        `profit` Tuple(Tuple(String, String), Tuple(String, String)),
        `profit_amt` Float64,
        `revenue` Tuple(Tuple(String, String), Tuple(String, String)),
        `revenue_amt` Float64,
    ),
    `atomic_arbed_dex_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `atomic_biggest_arb_profit`          Nullable(String),
    `atomic_biggest_arb_profit_amt`      Nullable(Float64),
    `atomic_biggest_arb_revenue`         Nullable(String),
    `atomic_biggest_arb_revenue_amt`     Nullable(Float64),

    -- sandwich
    `sandwich_bundle_count` UInt64,
    `sandwich_total_profit`                Float64,
    `sandwich_total_revenue`               Float64,
    `sandwich_average_profit_margin`       Float64,
    `sandwich_top_searcher_profit`         Nullable(String),
    `sandwich_top_searcher_profit_amt`     Nullable(Float64),
    `sandwich_top_searcher_revenue`        Nullable(String),
    `sandwich_top_searcher_revenue_amt`    Nullable(Float64),
    `sandwich_searcher_eoa_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `sandwich_searcher_eoa_count`              UInt64,
    `sandwich_mev_contract_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `sandwich_mev_contract_count`              UInt64,
    `sandwich_top_fund_profit`             Nullable(String),
    `sandwich_top_fund_profit_amt`         Nullable(Float64),
    `sandwich_top_fund_revenue`            Nullable(String),
    `sandwich_top_fund_revenue_amt`        Nullable(Float64),
    `sandwich_fund_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `sandwich_fund_count`                  UInt64,
    `sandwich_most_arbed_pool_profit`      Nullable(String),
    `sandwich_most_arbed_pool_profit_amt`  Nullable(Float64),
    `sandwich_most_arbed_pool_revenue`     Nullable(String),
    `sandwich_most_arbed_pool_revenue_amt` Nullable(Float64),
    `sandwich_most_arbed_pair_profit`      Tuple(Tuple(String, String), Tuple(String, String)),
    `sandwich_most_arbed_pair_profit_amt`  Nullable(Float64),
    `sandwich_most_arbed_pair_revenue`     Tuple(Tuple(String, String), Tuple(String, String)),
    `sandwich_most_arbed_pair_revenue_amt` Nullable(Float64),
    `sandwich_most_arbed_dex_profit`       Nullable(String),
    `sandwich_most_arbed_dex_profit_amt`   Nullable(Float64),
    `sandwich_most_arbed_dex_revenue`      Nullable(String),
    `sandwich_most_arbed_dex_revenue_amt`  Nullable(Float64),
    `sandwich_arbed_pool_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `sandwich_arbed_pair_all` Nested (
        `profit` Tuple(Tuple(String, String), Tuple(String, String)),
        `profit_amt` Float64,
        `revenue` Tuple(Tuple(String, String), Tuple(String, String)),
        `revenue_amt` Float64,
    ),
    `sandwich_arbed_dex_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `sandwich_biggest_arb_profit`          Nullable(String),
    `sandwich_biggest_arb_profit_amt`      Nullable(Float64),
    `sandwich_biggest_arb_revenue`         Nullable(String),
    `sandwich_biggest_arb_revenue_amt`     Nullable(Float64),

    -- jit
    `jit_bundle_count` UInt64,
    `jit_total_profit`                Float64,
    `jit_total_revenue`               Float64,
    `jit_average_profit_margin`       Float64,
    `jit_top_searcher_profit`         Nullable(String),
    `jit_top_searcher_profit_amt`     Nullable(Float64),
    `jit_top_searcher_revenue`        Nullable(String),
    `jit_top_searcher_revenue_amt`    Nullable(Float64),
    `jit_searcher_eoa_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_searcher_eoa_count`              UInt64,
    `jit_mev_contract_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_mev_contract_count`              UInt64,
    `jit_top_fund_profit`             Nullable(String),
    `jit_top_fund_profit_amt`         Nullable(Float64),
    `jit_top_fund_revenue`            Nullable(String),
    `jit_top_fund_revenue_amt`        Nullable(Float64),
    `jit_fund_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_fund_count`                  UInt64,
    `jit_most_arbed_pool_profit`      Nullable(String),
    `jit_most_arbed_pool_profit_amt`  Nullable(Float64),
    `jit_most_arbed_pool_revenue`     Nullable(String),
    `jit_most_arbed_pool_revenue_amt` Nullable(Float64),
    `jit_most_arbed_pair_profit`      Tuple(Tuple(String, String), Tuple(String, String)),
    `jit_most_arbed_pair_profit_amt`  Nullable(Float64),
    `jit_most_arbed_pair_revenue`     Tuple(Tuple(String, String), Tuple(String, String)),
    `jit_most_arbed_pair_revenue_amt` Nullable(Float64),
    `jit_most_arbed_dex_profit`       Nullable(String),
    `jit_most_arbed_dex_profit_amt`   Nullable(Float64),
    `jit_most_arbed_dex_revenue`      Nullable(String),
    `jit_most_arbed_dex_revenue_amt`  Nullable(Float64),
    `jit_arbed_pool_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_arbed_pair_all` Nested (
        `profit` Tuple(Tuple(String, String), Tuple(String, String)),
        `profit_amt` Float64,
        `revenue` Tuple(Tuple(String, String), Tuple(String, String)),
        `revenue_amt` Float64,
    ),
    `jit_arbed_dex_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_biggest_arb_profit`          Nullable(String),
    `jit_biggest_arb_profit_amt`      Nullable(Float64),
    `jit_biggest_arb_revenue`         Nullable(String),
    `jit_biggest_arb_revenue_amt`     Nullable(Float64),

    -- jit sandwich
    `jit_sandwich_bundle_count` UInt64,
    `jit_sandwich_total_profit`                Float64,
    `jit_sandwich_total_revenue`               Float64,
    `jit_sandwich_average_profit_margin`       Float64,
    `jit_sandwich_top_searcher_profit`         Nullable(String),
    `jit_sandwich_top_searcher_profit_amt`     Nullable(Float64),
    `jit_sandwich_top_searcher_revenue`        Nullable(String),
    `jit_sandwich_top_searcher_revenue_amt`    Nullable(Float64),
    `jit_sandwich_searcher_eoa_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_sandwich_searcher_eoa_count`              UInt64,
    `jit_sandwich_mev_contract_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_sandwich_mev_contract_count`              UInt64,
    `jit_sandwich_top_fund_profit`             Nullable(String),
    `jit_sandwich_top_fund_profit_amt`         Nullable(Float64),
    `jit_sandwich_top_fund_revenue`            Nullable(String),
    `jit_sandwich_top_fund_revenue_amt`        Nullable(Float64),
    `jit_sandwich_fund_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_sandwich_fund_count`                  UInt64,
    `jit_sandwich_most_arbed_pool_profit`      Nullable(String),
    `jit_sandwich_most_arbed_pool_profit_amt`  Nullable(Float64),
    `jit_sandwich_most_arbed_pool_revenue`     Nullable(String),
    `jit_sandwich_most_arbed_pool_revenue_amt` Nullable(Float64),
    `jit_sandwich_most_arbed_pair_profit`      Tuple(Tuple(String, String), Tuple(String, String)),
    `jit_sandwich_most_arbed_pair_profit_amt`  Nullable(Float64),
    `jit_sandwich_most_arbed_pair_revenue`     Tuple(Tuple(String, String), Tuple(String, String)),
    `jit_sandwich_most_arbed_pair_revenue_amt` Nullable(Float64),
    `jit_sandwich_most_arbed_dex_profit`       Nullable(String),
    `jit_sandwich_most_arbed_dex_profit_amt`   Nullable(Float64),
    `jit_sandwich_most_arbed_dex_revenue`      Nullable(String),
    `jit_sandwich_most_arbed_dex_revenue_amt`  Nullable(Float64),
    `jit_sandwich_arbed_pool_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_sandwich_arbed_pair_all` Nested (
        `profit` Tuple(Tuple(String, String), Tuple(String, String)),
        `profit_amt` Float64,
        `revenue` Tuple(Tuple(String, String), Tuple(String, String)),
        `revenue_amt` Float64,
    ),
    `jit_sandwich_arbed_dex_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `jit_sandwich_biggest_arb_profit`          Nullable(String),
    `jit_sandwich_biggest_arb_profit_amt`      Nullable(Float64),
    `jit_sandwich_biggest_arb_revenue`         Nullable(String),
    `jit_sandwich_biggest_arb_revenue_amt`     Nullable(Float64),

    -- cex_dex
    `cex_dex_bundle_count` UInt64,
    `cex_dex_total_profit`                Float64,
    `cex_dex_total_revenue`               Float64,
    `cex_dex_average_profit_margin`       Float64,
    `cex_dex_top_searcher_profit`         Nullable(String),
    `cex_dex_top_searcher_profit_amt`     Nullable(Float64),
    `cex_dex_top_searcher_revenue`        Nullable(String),
    `cex_dex_top_searcher_revenue_amt`    Nullable(Float64),
    `cex_dex_searcher_eoa_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `cex_dex_searcher_eoa_count`              UInt64,
    `cex_dex_mev_contract_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `cex_dex_mev_contract_count`              UInt64,
    `cex_dex_top_fund_profit`             Nullable(String),
    `cex_dex_top_fund_profit_amt`         Nullable(Float64),
    `cex_dex_top_fund_revenue`            Nullable(String),
    `cex_dex_top_fund_revenue_amt`        Nullable(Float64),
    `cex_dex_fund_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `cex_dex_fund_count`                  UInt64,
    `cex_dex_most_arbed_pool_profit`      Nullable(String),
    `cex_dex_most_arbed_pool_profit_amt`  Nullable(Float64),
    `cex_dex_most_arbed_pool_revenue`     Nullable(String),
    `cex_dex_most_arbed_pool_revenue_amt` Nullable(Float64),
    `cex_dex_most_arbed_pair_profit`      Tuple(Tuple(String, String), Tuple(String, String)),
    `cex_dex_most_arbed_pair_profit_amt`  Nullable(Float64),
    `cex_dex_most_arbed_pair_revenue`     Tuple(Tuple(String, String), Tuple(String, String)),
    `cex_dex_most_arbed_pair_revenue_amt` Nullable(Float64),
    `cex_dex_most_arbed_dex_profit`       Nullable(String),
    `cex_dex_most_arbed_dex_profit_amt`   Nullable(Float64),
    `cex_dex_most_arbed_dex_revenue`      Nullable(String),
    `cex_dex_most_arbed_dex_revenue_amt`  Nullable(Float64),
    `cex_dex_arbed_pool_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `cex_dex_arbed_pair_all` Nested (
        `profit` Tuple(Tuple(String, String), Tuple(String, String)),
        `profit_amt` Float64,
        `revenue` Tuple(Tuple(String, String), Tuple(String, String)),
        `revenue_amt` Float64,
    ),
    `cex_dex_arbed_dex_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `cex_dex_biggest_arb_profit`          Nullable(String),
    `cex_dex_biggest_arb_profit_amt`      Nullable(Float64),
    `cex_dex_biggest_arb_revenue`         Nullable(String),
    `cex_dex_biggest_arb_revenue_amt`     Nullable(Float64),

    -- liquidation
    `liquidation_bundle_count` UInt64,
    `liquidation_total_profit`                Float64,
    `liquidation_total_revenue`               Float64,
    `liquidation_average_profit_margin`       Float64,
    `liquidation_top_searcher_profit`         Nullable(String),
    `liquidation_top_searcher_profit_amt`     Nullable(Float64),
    `liquidation_top_searcher_revenue`        Nullable(String),
    `liquidation_top_searcher_revenue_amt`    Nullable(Float64),
    `liquidation_searcher_eoa_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `liquidation_searcher_eoa_count`              UInt64,
    `liquidation_mev_contract_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64,
    ),
    `liquidation_mev_contract_count`              UInt64,
    `liquidation_top_fund_profit`             Nullable(String),
    `liquidation_top_fund_profit_amt`         Nullable(Float64),
    `liquidation_top_fund_revenue`            Nullable(String),
    `liquidation_top_fund_revenue_amt`        Nullable(Float64),
    `liquidation_fund_all` Nested (
        `profit` String,
        `profit_amt` Float64,
        `revenue` String,
        `revenue_amt` Float64
    ),
    `liquidation_fund_count`                  UInt64,
    `most_liquidated_token_revenue`           Tuple(String, String),
    `most_liquidated_token_revenue_amt`       Nullable(Float64),
    `most_liquidated_token_profit`            Tuple(String, String),
    `most_liquidated_token_profit_amt`        Nullable(Float64),
    `liquidated_tokens` Nested (
        `revenue` Tuple(String, String),
        `revenue_amt` Float64,
        `profit` Tuple(String, String),
        `profit_amt` Float64
    ),
    `liquidated_biggest_arb_profit`        Nullable(String),
    `liquidated_biggest_arb_profit_amt`    Nullable(Float64),
    `liquidated_biggest_arb_revenue`       Nullable(String),
    `liquidated_biggest_arb_revenue_amt`   Nullable(Float64),
    `total_usd_liquidated` Float64,

    `builder_profit_usd`     Float64,
    `builder_profit_eth`     Float64,
    `builder_revenue_usd`    Float64,
    `builder_revenue_eth`    Float64,
    `builder_mev_profit_usd` Float64,
    `builder_mev_profit_eth` Float64,
    `builder_name`           Nullable(String),
    `builder_address`        String,
    `proposer_profit_usd`    Nullable(Float64),
    `proposer_profit_eth`    Nullable(Float64),
    
    `run_id` UInt64
) 
ENGINE = ReplicatedMergeTree('/clickhouse/eth_cluster0/tables/all/brontes/block_analysis', '{replica}')
PRIMARY KEY (`block_number`)
ORDER BY (`block_number`)
