name: Manual Benchmark

on:
  workflow_dispatch:
    inputs:
      benchmark_type:
        description: "Brontes Benchmarks"
        required: true
        default: "full"
        type: choice
        options:
          - full
          - quick
      features:
        description: "Features to enable (comma-separated)"
        required: false
        default: "sorella-server"

jobs:
  bench:
    strategy:
      fail-fast: false
      matrix:
        features: ["sorella-server"]
    runs-on: ubuntu-latest
    steps:
      - name: Get branch names.
        id: branch-names
        uses: tj-actions/branch-names@v8
      - name: Init ssh config
        run: |
          mkdir ~/.ssh/ 
          echo "${{ secrets.BASTION_SSH }}" > ~/.ssh/bastion 
          chmod 600 ~/.ssh/bastion 
          echo "${{ secrets.BRONTES_SSH }}" > ~/.ssh/brontes_server 
          chmod 600 ~/.ssh/brontes_server
          echo "${{ secrets.SSH_CONFIG }}" > ~/.ssh/config

      - name: cargo bench
        run: |
          ssh brontes_server -tt "bash --login -c '
            source ~/.bashrc
            mkdir -p ${{ steps.branch-names.outputs.current_branch }}-bench-${{ matrix.features }}
            cd ${{ steps.branch-names.outputs.current_branch }}-bench-${{ matrix.features }}
            git clone https://github.com/SorellaLabs/brontes.git
            cd brontes
            git pull
            git checkout ${{ steps.branch-names.outputs.current_branch }}
            ./scripts/run-tests.sh ${{ steps.branch-names.outputs.current_branch }} ${{ steps.branch-names.outputs.current_branch }}-bench-${{ matrix.features }} bench ${{ matrix.features }}
          '"

      - name: Cleanup on cancellation
        if: cancelled()
        run: |
          ssh brontes_server -tt "bash --login -c 'source ~/.bashrc
            set -x
            rm -rf /home/brontes-ci/${{ steps.branch-names.outputs.current_branch }}-bench-${{ matrix.features }}
            rm -rf /home/brontes-ci/data/${{ steps.branch-names.outputs.current_branch }}-bench-${{ matrix.features }}
          '"
