name: telegram bot - closed issue

on:
  issues:
    types:
      - closed
  workflow_dispatch:

jobs:
  new-issue:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download Rust Binary
      run: |
        gh release download -R SorellaLabs/github-utils -p Linux.tgz
        tar -xzf Linux.tgz
      env:
        GH_TOKEN: ${{ secrets.CI }}

    - name: Run Rust Binary
      run: ./Linux/github-actions telegram-bot -t ${{ secrets.TELEGRAM_BOT_TOKEN }} -g ${{ secrets.G_API_KEY }} --repo ${{ vars.REPO }} -s ${{ vars.PROJECT }} -c --number ${{ github.event.issue.number }}
