on:
  push:
    branches:
    - main
  pull_request:

name: CI

jobs:
  print_repo_name:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      - name: Echo repository name
        run: echo "Repository name is ${{ github.repository }}"
