[package]
name = "poirot-labeller"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reth-primitives.workspace = true
sorella-db-clients = { git = "https://github.com/SorellaLabs/Database", package = "sorella-db-clients", branch = "main" }
<<<<<<< HEAD

=======
>>>>>>> main
# serde
serde = { workspace = true, features = ["derive"]}
serde_json.workspace = true
serde_with = { version = "3.3.0", features = ["macros"] }

# error handling
thiserror.workspace = true

# numbers
malachite.workspace = true
hyper-tls = "0.5.0"
poirot-core.workspace = true
hyper.workspace = true
clickhouse = { git = "https://github.com/SorellaLabs/clickhouse.rs" }
futures = "0.3.28"
tokio.workspace = true
poirot-metrics.workspace = true
